# -*- coding: utf-8 -*-
"""Week 8 - Sales Forecasting Analysis System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnOWOUgviJS_8Z6S-3hDUHhtbqhVhFPe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import plotly.express as px

"""**1. Data Collection**"""

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

print("Shape:", data.shape)
print("\nColumn Names:")
print(data.columns)
data

"""**2. Data Cleaning & Preprocessing**"""

print("Original Shape:", data.shape)

data = data[['Order Date', 'Region', 'Product ID', 'Sales', 'State']]

data = data.rename(columns={
    'Order Date': 'Date',
    'Product ID': 'Item',
    'State': 'Store'
})

print("New Shape:", data.shape)
data

print(data['Date'].dtype)

data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

print(data['Date'].dtype)

data

data = data.drop_duplicates()

data = data.dropna()

data.reset_index(drop=True, inplace=True)

data.info()

total_sales = data['Sales'].sum()
print("Total Sales:", total_sales)

average_sales = data['Sales'].mean()
print("Average Sales:", average_sales)

max_sales = data['Sales'].max()
min_sales = data['Sales'].min()
print("Max Sales:", max_sales)
print("Min Sales:", min_sales)

fig = px.histogram(
    data,
    x="Sales",
    nbins=40,
    title="Sales Distribution",
    marginal="box",
)

fig.show()

"""**4. Sales Trend Analysis**

*Analyze sales over time*
"""

sales_over_time = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    sales_over_time,
    x='Date',
    y='Sales',
    title='Sales Over Time'
)

fig.update_layout(
    xaxis_title='Date',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

"""*Identify seasonal trends*"""

data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Month_Name'] = data['Date'].dt.strftime('%b')

data

monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

fig = px.line(
    monthly_sales,
    x="Month_Name",
    y="Sales",
    color="Year",
    markers=True,
    title="Monthly Sales Trend (Seasonal Analysis)"
)

fig.show()

"""*Detect peak sales periods*"""

peak_months = monthly_sales.sort_values(by='Sales', ascending=False)

peak_months.head(10)

top_months = peak_months.head(10)

top_months = peak_months.head(10)

fig = px.bar(
    top_months,
    x="Month_Name",
    y="Sales",
    color="Year",
    title="Top Peak Sales Months"
)

fig.show()

"""**5. Store/Product Analysis**

*Compare sales across stores*
"""

store_sales = data.groupby('Store')['Sales'].sum().sort_values(ascending=False).reset_index()

fig = px.bar(
    store_sales.head(10),
    x='Store',
    y='Sales',
    title='Top 10 Stores by Total Sales',
    color='Sales',
    color_continuous_scale='viridis'
)

fig.update_layout(
    xaxis_title='Store',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

"""*Identify best-selling products*"""

product_sales = data.groupby('Item')['Sales'].sum().sort_values(ascending=False).reset_index()

fig = px.bar(
    product_sales.head(10),
    x='Item',
    y='Sales',
    title='Top 10 Products by Total Sales',
    color='Sales',
    color_continuous_scale='magma'
)

fig.update_layout(
    xaxis_title='Product',
    yaxis_title='Total Sales',
    template='plotly_white'
)

fig.show()

"""*Analyze low-performing products*"""

product_sales = data.groupby('Item')['Sales'].sum().reset_index()

low_performing_products = product_sales.sort_values(by='Sales', ascending=True)

low_performing_products.head(10)

bottom_products = low_performing_products.head(10)

fig = px.bar(
    bottom_products,
    x='Item',
    y='Sales',
    title='Lowest Performing Products (Bottom 10)',
    color='Sales',
    color_continuous_scale='Reds'
)

fig.update_layout(
    xaxis_title='Product ID',
    yaxis_title='Total Sales',
    xaxis_tickangle=45
)

fig.show()

"""**6. Time-Based Analysis**

*Daily Sales Trends*
"""

daily_sales = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    daily_sales,
    x='Date',
    y='Sales',
    title='Daily Sales Trends',
    markers=True
)
fig.show()

"""*Monthly Sales Trend*"""

data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Month_Name'] = data['Date'].dt.strftime('%b')

monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

monthly_sales = monthly_sales.sort_values(by=['Year','Month'])

fig = px.line(
    monthly_sales,
    x='Month_Name',
    y='Sales',
    color='Year',
    markers=True,
    title='Monthly Sales Trends'
)
fig.show()

"""*Yearly Sales Trend*"""

yearly_sales = data.groupby('Year')['Sales'].sum().reset_index()

fig = px.bar(
    yearly_sales,
    x='Year',
    y='Sales',
    text='Sales',
    title='Yearly Sales Growth Patterns',
    color='Sales',
    color_continuous_scale='Viridis'
)
fig.show()

"""**7. Relationship Analysis**

*Data VS Sales*
"""

date_sales = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.scatter(
    date_sales,
    x='Date',
    y='Sales',
    title='Date vs Sales Relationship',
    trendline='ols'
)

fig.show()

"""*Store VS Sales*"""

store_sales = data.groupby('Store')['Sales'].sum().reset_index()

fig = px.bar(
    store_sales,
    x='Store',
    y='Sales',
    color='Sales',
    title='Store vs Sales Relationship',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

"""*Product VS Sales*"""

product_sales = data.groupby('Item')['Sales'].sum().reset_index()

top_products = product_sales.sort_values(by='Sales', ascending=False).head(15)

fig = px.bar(
    top_products,
    x='Item',
    y='Sales',
    color='Sales',
    title='Product vs Sales Relationship (Top 15 Products)',
    color_continuous_scale='Viridis'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

"""*Identify Patterns Affecting Sales*"""

correlation = data[['Sales','Year','Month']].corr()

fig = px.imshow(
    correlation,
    text_auto=True,
    title='Correlation Between Time and Sales'
)

fig.show()

"""**8. Data Visualization**

*Line charts → Sales over time*
"""

sales_over_time = data.groupby('Date')['Sales'].sum().reset_index()

fig = px.line(
    sales_over_time,
    x='Date',
    y='Sales',
    title='Sales Over Time',
    markers=True
)

fig.show()

"""*Bar charts → Store/Product comparison*"""

store_sales = data.groupby('Store')['Sales'].sum().reset_index()

fig = px.bar(
    store_sales,
    x='Store',
    y='Sales',
    color='Sales',
    title='Store Sales Comparison',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

"""*Histograms → Sales distribution*"""

fig = px.histogram(
    data,
    x='Sales',
    nbins=40,
    title='Sales Distribution Histogram',
    marginal='box'
)

fig.show()

"""*Box plots → Outlier detection*"""

fig = px.box(
    data,
    y='Sales',
    title='Sales Outlier Detection'
)

fig.show()

"""*Heatmaps → Correlation*"""

correlation = data[['Sales','Year','Month']].corr()

fig = px.imshow(
    correlation,
    text_auto=True,
    title='Correlation Heatmap'
)

fig.show()

"""**9. Business Insights**

*Identify Peak Sales Seasons*
"""

monthly_sales = data.groupby(['Year','Month','Month_Name'])['Sales'].sum().reset_index()

peak_seasons = monthly_sales.sort_values(by='Sales', ascending=False)

peak_seasons.head(10)

top_peak_months = peak_seasons.head(10)

fig = px.bar(
    top_peak_months,
    x='Month_Name',
    y='Sales',
    color='Year',
    title='Peak Sales Seasons'
)

fig.show()

"""*Detect High-Performing Stores*"""

store_sales = data.groupby('Store')['Sales'].sum().reset_index()

top_stores = store_sales.sort_values(by='Sales', ascending=False).head(10)

top_stores

fig = px.bar(
    top_stores,
    x='Store',
    y='Sales',
    color='Sales',
    title='Top Performing Stores',
    color_continuous_scale='Viridis'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()

"""*Understand Sales Fluctuations*"""

product_sales = data.groupby('Item')['Sales'].sum().reset_index()

top_products = product_sales.sort_values(by='Sales', ascending=False).head(10)

top_products

fig = px.bar(
    top_products,
    x='Item',
    y='Sales',
    color='Sales',
    title='Top Performing Products',
    color_continuous_scale='Blues'
)

fig.update_layout(xaxis_tickangle=45)

fig.show()